import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Basir",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Tirelire",
      category: "Decor",
      image: "/images/p1.jpg",
      price: 40,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "Tirelire d'argent",
    },
    {
      name: "Tajine de présentation",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 150,
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: "Tajine de présentation",
    },
    {
      name: "Tajine culinaire",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 90,
      countInStock: 0,
      rating: 4.8,
      numReviews: 17,
      description: "Tajine culinaire",
    },
    {
      name: "Berrada",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description: "Berrada",
    },
    {
      name: "Copa de fruits",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: "Copa de fruits",
    },
    {
      name: "Fontaine",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 199,
      countInStock: 12,
      rating: 4.5,
      numReviews: 15,
      description: "Fontaine",
    },
  ],
};
export default data;
